---

version: "3.8"

services:
  application:
    image: study-api_img
    networks:
      - springboot-db-net
    ports:
      - "9191:9191"
    depends_on:
      - mysqldb


  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    networks: 
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root@1234
      - MYSQL_DATABASE=online_plateform

networks:
  springboot-db-net:

...
